dist: bionic

env:
  global:
    - TAG=pkskubeflow/docker-compose:v1.0
    - CODE_TAG=master

arch:
  - arm64

services:
  - docker

before_install:
  - git clone -b ${CODE_TAG} --depth 1 https://github.com/docker/compose.git
  - git clone  --depth 1 https://github.com/kubeflow-pk/docker-compose-arm64.git

script:
  - rm compose/script/build/linux
  - mv docker-compose-arm64/linux compose/script/build/
  - cd compose/
  - ./script/build/linux
  - docker login -u ${DOCKER_USER} -p ${DOCKER_PWD}
  - docker push ${TAG}
