dist: bionic

env:
  global:
    - IMAGE=pkskubeflow/docker-compose:v1.0
    - CODE_TAG=master

arch:
  - amd64

services:
  - docker

before_install:
  - git clone -b ${CODE_TAG} --depth 1 https://github.com/ubiquiti/docker-compose-aarch64.git

script:
  - cd docker-compose-aarch64
  - docker build -t ${IMAGE} .
  - docker login -u ${DOCKER_USER} -p ${DOCKER_PWD}
  - docker push ${IMAGE}
