#!/bin/bash

set -ex

./script/clean

DOCKER_COMPOSE_GITSHA="$(script/build/write-git-sha)"
TAG="docker/compose:tmp-glibc-linux-binary-${DOCKER_COMPOSE_GITSHA}"

docker build -t "${TAG}" . \
       --build-arg BUILD_PLATFORM=centos \
       --build-arg GIT_COMMIT="${DOCKER_COMPOSE_GITSHA}"
